Update eval_mteb.py
added the closed square bracket on line 1162. which was throwing the error given below: 
gritlm/evaluation/eval_mteb.py", line 1162
    tasks = [(t.metadata.name, t.metadata.type) for t in MTEB(**kwargs).tasks
            ^
SyntaxError: '[' was never closed

and this occurs while running the command:
`python evaluation/eval_mteb.py --model_name_or_path GritLM/GritLM-7B --task_types Classification,Clustering,PairClassification,Reranking,Retrieval,STS,Summarization --batch_size 32`